### ISSUE TITLE
All output images are 0b

### ISSUE THREAD

**Issue by ostat** [devil-tamachan/movie-thumbnailer#1]
Hi,

I tried switching from the old mtn and to this version. All of the videos I have tried produce 0b images. Have you experienced this? There is no error reported.

**Comment by devil-tamachan** [comment]
Hi,
Thank you for your bug-report.

You need ImageMagick-6.9.0-Q16-x86-dll.exe. (not found now)
I released new version. Please try it instead. https://github.com/devil-tamachan/movie-thumbnailer/releases
